import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	backdrop: {
		...StyleSheet.absoluteFillObject,
		backgroundColor: "rgba(0,0,0,0.6)",
	},
	panel: {
		position: "absolute",
		bottom: 0,
		left: 0,
		right: 0,
		backgroundColor: "#0F172A",
		borderTopLeftRadius: 20,
		borderTopRightRadius: 20,
		borderTopWidth: 1,
		borderColor: "rgba(148,163,184,0.2)",
		paddingBottom: 36,
		maxHeight: "80%",
	},
	handle: {
		alignSelf: "center",
		width: 36,
		height: 4,
		borderRadius: 2,
		backgroundColor: "rgba(148,163,184,0.35)",
		marginTop: 10,
		marginBottom: 6,
	},
	closeBtn: {
		position: "absolute",
		top: 12,
		right: 16,
		padding: 6,
		zIndex: 1,
	},
	closeIcon: { width: 22, height: 22 },
	content: {
		paddingHorizontal: 20,
		paddingTop: 8,
		paddingBottom: 8,
		gap: 16,
	},
	topRow: {
		flexDirection: "row",
		gap: 18,
		alignItems: "flex-start",
	},
	imageWrapper: {
		alignItems: "center",
		gap: 8,
	},
	cardImage: {
		width: 120,
		height: 168,
		borderRadius: 10,
	},
	cardImageFallback: {
		width: 120,
		height: 168,
		borderRadius: 10,
		borderWidth: 2,
		backgroundColor: "#F8FAFC",
		justifyContent: "center",
		alignItems: "center",
		gap: 4,
	},
	fallbackRank: {
		fontSize: 28,
		fontWeight: "bold",
	},
	fallbackSuit: {
		fontSize: 34,
	},
	valueBadge: {
		paddingHorizontal: 14,
		paddingVertical: 4,
		borderRadius: 20,
		borderWidth: 1,
		backgroundColor: "rgba(15,23,42,0.6)",
	},
	valueText: {
		fontSize: 13,
		fontWeight: "700",
		letterSpacing: 0.3,
	},
	infoCol: {
		flex: 1,
		gap: 10,
		paddingTop: 2,
	},
	classBadge: {
		flexDirection: "row",
		alignItems: "center",
		alignSelf: "flex-start",
		gap: 6,
		paddingHorizontal: 10,
		paddingVertical: 4,
		borderRadius: 20,
		borderWidth: 1,
	},
	suitSymbolSmall: {
		fontSize: 14,
		fontWeight: "700",
	},
	className: {
		fontSize: 12,
		fontWeight: "800",
		letterSpacing: 0.8,
		textTransform: "uppercase",
	},
	heroName: {
		color: "#F1F5F9",
		fontFamily: "IMFellEnglish-Regular",
		fontSize: 22,
		fontWeight: "700",
		letterSpacing: 0.5,
	},
	rankSubtitle: {
		color: "#64748B",
		fontSize: 13,
		fontWeight: "500",
		letterSpacing: 0.3,
		marginTop: -6,
	},
	divider: {
		height: 1,
		backgroundColor: "rgba(148,163,184,0.15)",
	},
	sectionLabel: {
		color: "#64748B",
		fontSize: 11,
		fontWeight: "700",
		letterSpacing: 1,
		textTransform: "uppercase",
	},
	powerBox: {
		gap: 4,
	},
	powerBoxImmune: {
		backgroundColor: "rgba(239,68,68,0.08)",
		borderWidth: 1,
		borderColor: "rgba(239,68,68,0.25)",
		paddingHorizontal: 10,
		paddingVertical: 8,
		borderRadius: 10,
	},
	immuneTag: {
		color: "#F87171",
		fontSize: 12,
		fontWeight: "700",
		letterSpacing: 0.3,
	},
	powerDesc: {
		color: "#94A3B8",
		fontSize: 13,
		lineHeight: 19,
	},
	powerDescImmune: {
		color: "#CBD5E1",
	},
	loreBlock: {
		borderLeftWidth: 3,
		paddingLeft: 12,
		paddingVertical: 4,
		gap: 4,
	},
	loreLabel: {
		color: "#CBD5E1",
		fontFamily: "IMFellEnglish-Regular",
		fontSize: 13,
		fontWeight: "700",
		letterSpacing: 0.5,
	},
	loreText: {
		color: "#64748B",
		fontSize: 12,
		lineHeight: 18,
		fontStyle: "italic",
	},
});
