import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	container: { flex: 1 },
	overlay: {
		flex: 1,
		backgroundColor: "rgba(0,0,0,0.65)",
	},
	scroll: { flex: 1 },
	scrollContent: {
		paddingHorizontal: 16,
		paddingBottom: 16,
		gap: 20,
	},
	introBlock: {
		alignItems: "center",
		paddingVertical: 20,
		gap: 6,
	},
	crownImage: {
		width: 64,
		height: 64,
		marginBottom: 4,
	},
	gameName: {
		fontFamily: "IMFellEnglish-Regular",
		fontSize: 36,
		fontWeight: "900",
		color: "#FBBF24",
		letterSpacing: 6,
	},
	gameSubtitle: {
		color: "#94A3B8",
		fontSize: 13,
		letterSpacing: 0.5,
	},
	section: {
		backgroundColor: "rgba(15,23,42,0.75)",
		borderRadius: 14,
		padding: 16,
		gap: 12,
		borderWidth: 1,
		borderColor: "rgba(148,163,184,0.12)",
	},
	sectionTitle: {
		fontFamily: "IMFellEnglish-Regular",
		color: "#FBBF24",
		fontSize: 17,
		fontWeight: "700",
		letterSpacing: 0.5,
		borderBottomWidth: 1,
		borderBottomColor: "rgba(251,191,36,0.2)",
		paddingBottom: 8,
	},
	bodyText: {
		color: "#CBD5E1",
		fontSize: 14,
		lineHeight: 22,
	},
	stepList: { gap: 12 },
	step: {
		flexDirection: "row",
		gap: 12,
		alignItems: "flex-start",
	},
	stepNum: {
		width: 28,
		height: 28,
		borderRadius: 14,
		backgroundColor: "rgba(251,191,36,0.2)",
		borderWidth: 1,
		borderColor: "#FBBF24",
		justifyContent: "center",
		alignItems: "center",
		flexShrink: 0,
	},
	stepNumText: {
		color: "#FBBF24",
		fontWeight: "700",
		fontSize: 13,
	},
	stepBody: { flex: 1, gap: 2 },
	stepTitle: {
		color: "#F1F5F9",
		fontWeight: "700",
		fontSize: 14,
	},
	stepDesc: {
		color: "#94A3B8",
		fontSize: 13,
		lineHeight: 20,
	},
	suitList: { gap: 12 },
	suitRow: {
		flexDirection: "row",
		alignItems: "flex-start",
		gap: 12,
	},
	suitBadge: {
		width: 40,
		height: 40,
		borderRadius: 10,
		borderWidth: 1,
		justifyContent: "center",
		alignItems: "center",
		flexShrink: 0,
	},
	suitSymbol: { fontSize: 20, fontWeight: "700" },
	suitInfo: { flex: 1, gap: 2 },
	suitName: { fontSize: 14, fontWeight: "700" },
	suitPower: { color: "#94A3B8", fontSize: 13, lineHeight: 19 },
	immuneExamples: { gap: 6 },
	immuneRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 10,
	},
	immuneSymbol: { fontSize: 18, fontWeight: "700", width: 24 },
	immuneLabel: { color: "#94A3B8", fontSize: 13 },
	enemyRow: {
		flexDirection: "row",
		alignItems: "flex-start",
		gap: 14,
		paddingVertical: 4,
		borderBottomWidth: 1,
		borderBottomColor: "rgba(148,163,184,0.1)",
	},
	enemyRankBadge: {
		width: 36,
		height: 36,
		borderRadius: 8,
		backgroundColor: "rgba(251,191,36,0.15)",
		borderWidth: 1,
		borderColor: "rgba(251,191,36,0.4)",
		justifyContent: "center",
		alignItems: "center",
	},
	enemyRankText: {
		color: "#FBBF24",
		fontFamily: "IMFellEnglish-Regular",
		fontSize: 18,
		fontWeight: "700",
	},
	enemyInfo: { flex: 1, gap: 2 },
	enemyLabel: { color: "#F1F5F9", fontWeight: "700", fontSize: 14 },
	enemyStats: { fontSize: 13 },
	statHp: { color: "#4ADE80" },
	statAtk: { color: "#FBBF24" },
	enemyImmunity: { color: "#64748B", fontSize: 12 },
	comboExamples: {
		gap: 6,
		backgroundColor: "rgba(0,0,0,0.25)",
		borderRadius: 8,
		padding: 10,
	},
	tableRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		paddingVertical: 3,
	},
	tableLabel: { color: "#CBD5E1", fontSize: 13 },
	tableValue: { color: "#94A3B8", fontSize: 13, flex: 1, textAlign: "right" },
	endConditions: { gap: 10 },
	victoryBlock: {
		backgroundColor: "rgba(34,197,94,0.1)",
		borderRadius: 10,
		padding: 12,
		gap: 4,
		borderLeftWidth: 3,
		borderLeftColor: "#22C55E",
	},
	victoryTitle: { color: "#22C55E", fontWeight: "700", fontSize: 15 },
	defeatBlock: {
		backgroundColor: "rgba(239,68,68,0.1)",
		borderRadius: 10,
		padding: 12,
		gap: 4,
		borderLeftWidth: 3,
		borderLeftColor: "#EF4444",
	},
	defeatTitle: { color: "#EF4444", fontWeight: "700", fontSize: 15 },
	endText: { color: "#CBD5E1", fontSize: 13, lineHeight: 20 },
});
