import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	// Botão flutuante de alternância
	fab: {
		position: "absolute",
		right: 16,
		bottom: 16,
		width: 52,
		height: 52,
		borderRadius: 26,
		backgroundColor: "rgba(10,7,3,0.96)",
		borderWidth: 1,
		borderColor: "rgba(232,213,163,0.5)",
		alignItems: "center",
		justifyContent: "center",
		zIndex: 30,
	},
	badge: {
		position: "absolute",
		top: -4,
		right: -4,
		minWidth: 20,
		height: 20,
		borderRadius: 10,
		paddingHorizontal: 5,
		backgroundColor: "#EF4444",
		alignItems: "center",
		justifyContent: "center",
	},
	badgeText: {
		color: "#fff",
		fontSize: 11,
		fontWeight: "700",
	},
	// Painel
	panel: {
		position: "absolute",
		backgroundColor: "rgba(10,7,3,0.98)",
		borderColor: "rgba(232,213,163,0.4)",
		zIndex: 31,
	},
	panelMobile: {
		left: 0,
		right: 0,
		bottom: 0,
		height: "62%",
		borderTopWidth: 1,
		borderTopLeftRadius: 18,
		borderTopRightRadius: 18,
	},
	panelTablet: {
		top: 0,
		right: 0,
		bottom: 0,
		width: 340,
		borderLeftWidth: 1,
	},
	// Docado (desktop): ocupa a coluna direita do layout, sem sobrepor o jogo.
	panelDocked: {
		position: "relative",
		flex: 1,
		borderLeftWidth: 1,
	},
	header: {
		flexDirection: "row",
		alignItems: "center",
		paddingHorizontal: 16,
		paddingVertical: 12,
		borderBottomWidth: 1,
		borderBottomColor: "rgba(232,213,163,0.18)",
	},
	headerTitle: {
		flex: 1,
		fontFamily: "Cinzel",
		fontSize: 15,
		color: "#E8D5A3",
		letterSpacing: 1,
	},
	list: {
		flex: 1,
	},
	listContent: {
		padding: 12,
		gap: 8,
	},
	empty: {
		flex: 1,
		alignItems: "center",
		justifyContent: "center",
		padding: 24,
	},
	emptyText: {
		fontFamily: "IMFellEnglish",
		fontSize: 14,
		color: "#64748B",
		textAlign: "center",
	},
	systemRow: {
		alignItems: "center",
		paddingVertical: 2,
	},
	systemText: {
		fontFamily: "IMFellEnglish",
		fontSize: 12,
		color: "#64748B",
		fontStyle: "italic",
	},
	bubble: {
		maxWidth: "85%",
		borderRadius: 12,
		paddingHorizontal: 12,
		paddingVertical: 8,
		backgroundColor: "rgba(255,255,255,0.06)",
	},
	bubbleOwn: {
		alignSelf: "flex-end",
		backgroundColor: "rgba(180,130,60,0.35)",
		borderWidth: 1,
		borderColor: "rgba(232,213,163,0.4)",
	},
	bubbleOther: {
		alignSelf: "flex-start",
	},
	author: {
		fontFamily: "Cinzel",
		fontSize: 11,
		color: "#E8D5A3",
		marginBottom: 2,
	},
	bubbleText: {
		fontFamily: "IMFellEnglish",
		fontSize: 15,
		color: "#E2EAF4",
		lineHeight: 20,
	},
	inputRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		padding: 12,
		borderTopWidth: 1,
		borderTopColor: "rgba(232,213,163,0.18)",
	},
	input: {
		flex: 1,
		backgroundColor: "rgba(255,255,255,0.1)",
		borderRadius: 10,
		borderWidth: 1,
		borderColor: "rgba(232,213,163,0.4)",
		color: "#F0E0B0",
		fontFamily: "IMFellEnglish",
		fontSize: 15,
		paddingHorizontal: 12,
		paddingVertical: 9,
		maxHeight: 96,
	},
	sendBtn: {
		width: 44,
		height: 44,
		borderRadius: 10,
		backgroundColor: "rgba(180,130,60,0.5)",
		borderWidth: 1,
		borderColor: "rgba(232,213,163,0.8)",
		alignItems: "center",
		justifyContent: "center",
	},
	sendBtnDisabled: {
		opacity: 0.4,
	},
});
