import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	backdrop: {
		...StyleSheet.absoluteFillObject,
		backgroundColor: "rgba(0,0,0,0.6)",
	},
	backdropFill: {
		...StyleSheet.absoluteFillObject,
	},
	panel: {
		position: "absolute",
		bottom: 0,
		left: 0,
		right: 0,
		backgroundColor: "#0F172A",
		borderTopLeftRadius: 20,
		borderTopRightRadius: 20,
		borderTopWidth: 1,
		borderColor: "rgba(148,163,184,0.2)",
		paddingBottom: 48,
		paddingHorizontal: 24,
	},
	handle: {
		alignSelf: "center",
		width: 36,
		height: 4,
		borderRadius: 2,
		backgroundColor: "rgba(148,163,184,0.35)",
		marginTop: 10,
		marginBottom: 20,
	},
	title: {
		color: "#94A3B8",
		fontSize: 11,
		fontWeight: "700",
		letterSpacing: 1.2,
		textTransform: "uppercase",
		marginBottom: 16,
	},
	divider: {
		height: 1,
		backgroundColor: "rgba(148,163,184,0.12)",
		marginVertical: 4,
	},
	row: {
		flexDirection: "row",
		alignItems: "center",
		gap: 14,
		paddingVertical: 14,
	},
	rowIcon: {
		color: "#F1F5F9",
		fontSize: 20,
		width: 24,
		textAlign: "center",
	},
	rowLabel: {
		color: "#F1F5F9",
		fontSize: 16,
		fontWeight: "600",
	},
	rowLabelMuted: {
		color: "#64748B",
	},
	volumeRow: {
		gap: 10,
		paddingVertical: 12,
	},
	volumeHeader: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
	},
	volumeLabel: {
		color: "#F1F5F9",
		fontSize: 15,
		fontWeight: "600",
		flex: 1,
	},
	volumePct: {
		color: "#64748B",
		fontSize: 13,
		fontWeight: "600",
		minWidth: 36,
		textAlign: "right",
	},
	sliderHitArea: {
		height: 44,
		justifyContent: "center",
	},
	sliderTrack: {
		height: 6,
		borderRadius: 3,
		backgroundColor: "rgba(148,163,184,0.2)",
	},
	sliderFill: {
		position: "absolute",
		left: 0,
		top: 0,
		bottom: 0,
		borderRadius: 3,
		backgroundColor: "#C084FC",
	},
	sliderThumb: {
		position: "absolute",
		width: 18,
		height: 18,
		borderRadius: 9,
		backgroundColor: "#F1F5F9",
		top: -6,
		marginLeft: -9,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.3,
		shadowRadius: 3,
		elevation: 4,
	},
});
