import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	container: { flex: 1 },
	overlay: {
		flex: 1,
		backgroundColor: "rgba(0, 0, 0, 0.55)",
		justifyContent: "space-between",
	},
	frame: {
		flex: 1,
		width: "100%",
		alignSelf: "center",
	},
	frameDesktop: {
		backgroundColor: "rgba(2,6,23,0.16)",
	},
	statusBar: {
		position: "absolute",
		top: 50,
		left: 0,
		right: 0,
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "flex-end",
		gap: 12,
		zIndex: 10,
	},
	statusItem: { alignItems: "center", gap: 5 },
	statusCard: {
		width: 49,
		height: 70,
		borderColor: "rgb(5, 71, 84)",
		borderWidth: 3,
		borderRadius: 8,
		overflow: "hidden",
	},
	statusCardImg: { width: "100%", height: "100%" },
	statusCardOverlay: {
		...StyleSheet.absoluteFillObject,
		justifyContent: "center",
		alignItems: "center",
	},
	deckLabel: {
		color: "rgba(148,163,184,0.8)",
		fontSize: 9,
		fontWeight: "600",
		letterSpacing: 0.8,
		textTransform: "uppercase",
	},
	center: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		paddingTop: 90,
	},
	handSection: {
		width: "100%",
		alignSelf: "center",
		// Camada interativa (cartas + botões) acima do inimigo/decoração — em telas
		// baixas (tablet horizontal) o EnemyCard pode transbordar e capturar o toque.
		zIndex: 20,
	},
	error: {
		color: "#FCA5A5",
		fontSize: 12,
		textAlign: "center",
		marginBottom: 4,
		paddingHorizontal: 16,
	},
	participantsSidebar: {
		position: "absolute",
		top: 130,
		right: 8,
		width: "auto",
		gap: 8,
		zIndex: 10,
	},
	participantsTurnCard: {
		borderRadius: 12,
		borderWidth: 1,
		paddingHorizontal: 10,
		paddingVertical: 8,
		backgroundColor: "rgba(2,6,23,0.28)",
	},
	participantsTurnLabel: {
		fontFamily: "Cinzel",
		fontSize: 12,
		color: "rgba(232,213,163,0.62)",
		letterSpacing: 0.7,
		textTransform: "uppercase",
		marginBottom: 4,
	},
	participantsTurnRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 6,
	},
	participantsTurnDot: {
		width: 6,
		height: 6,
		borderRadius: 999,
		flexShrink: 0,
	},
	participantsTurnValue: {
		flexShrink: 1,
		fontFamily: "IMFellEnglish",
		fontSize: 16,
		lineHeight: 16,
	},
	participantsTurnSuffix: {
		fontFamily: "IMFellEnglish",
		fontSize: 16,
		lineHeight: 16,
		color: "rgba(203,213,225,0.72)",
	},
	participantsList: {
		gap: 6,
	},
	participantCard: {
		alignItems: "flex-start",
		justifyContent: "space-between",
		paddingHorizontal: 8,
		paddingVertical: 6,
		borderRadius: 10,
		borderWidth: 1,
		backgroundColor: "rgba(2,6,23,0.8)",
		gap: 8,
	},
	participantCardWaiting: {
		borderWidth: 0,
		opacity: 0.76,
	},
	participantIdentity: {
		flex: 1,
		flexDirection: "row",
		alignItems: "center",
		gap: 6,
		minWidth: 0,
	},
	participantDot: {
		width: 5,
		height: 5,
		borderRadius: 999,
		flexShrink: 0,
	},
	participantName: {
		flex: 1,
		fontFamily: "IMFellEnglish",
		fontSize: 16,
		lineHeight: 15,
		color: "rgba(203,213,225,0.92)",
	},
	participantCountPill: {
		minWidth: 24,
		paddingHorizontal: 6,
		paddingVertical: 2,
		borderRadius: 999,
		alignItems: "center",
	},
	participantCount: {
		fontFamily: "Cinzel",
		fontSize: 14,
		lineHeight: 13,
		color: "rgba(203,213,225,0.72)",
	},
});
